// This file is part of Acala.

// Copyright (C) 2020-2024 Acala Foundation.
// SPDX-License-Identifier: GPL-3.0-or-later WITH Classpath-exception-2.0

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

//! Autogenerated weights for orml_authority
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-05-15, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `ip-172-31-43-79`, CPU: `Intel(R) Xeon(R) Platinum 8375C CPU @ 2.90GHz`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// target/production/acala
// benchmark
// pallet
// --chain=dev
// --steps=50
// --repeat=20
// --pallet=*
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --template=./templates/runtime-weight-template.hbs
// --output=./runtime/mandala/src/weights/

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for orml_authority.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> orml_authority::WeightInfo for WeightInfo<T> {
	fn dispatch_as() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `965`
		//  Estimated: `0`
		// Minimum execution time: 17_142 nanoseconds.
		Weight::from_parts(17_657_000, 0)
	}
	// Storage: Authority NextTaskIndex (r:1 w:1)
	// Proof Skipped: Authority NextTaskIndex (max_values: Some(1), max_size: None, mode: Measured)
	// Storage: Scheduler Lookup (r:1 w:1)
	// Proof: Scheduler Lookup (max_values: None, max_size: Some(48), added: 2523, mode: MaxEncodedLen)
	// Storage: Scheduler Agenda (r:1 w:1)
	// Proof: Scheduler Agenda (max_values: None, max_size: Some(39213), added: 41688, mode: MaxEncodedLen)
	fn schedule_dispatch_without_delay() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1111`
		//  Estimated: `48787`
		// Minimum execution time: 32_486 nanoseconds.
		Weight::from_parts(33_355_000, 48787)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	// Storage: Authority NextTaskIndex (r:1 w:1)
	// Proof Skipped: Authority NextTaskIndex (max_values: Some(1), max_size: None, mode: Measured)
	// Storage: Scheduler Lookup (r:1 w:1)
	// Proof: Scheduler Lookup (max_values: None, max_size: Some(48), added: 2523, mode: MaxEncodedLen)
	// Storage: Scheduler Agenda (r:1 w:1)
	// Proof: Scheduler Agenda (max_values: None, max_size: Some(39213), added: 41688, mode: MaxEncodedLen)
	fn schedule_dispatch_with_delay() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1111`
		//  Estimated: `48787`
		// Minimum execution time: 33_246 nanoseconds.
		Weight::from_parts(34_508_000, 48787)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	// Storage: Scheduler Lookup (r:1 w:1)
	// Proof: Scheduler Lookup (max_values: None, max_size: Some(48), added: 2523, mode: MaxEncodedLen)
	// Storage: Scheduler Agenda (r:2 w:2)
	// Proof: Scheduler Agenda (max_values: None, max_size: Some(39213), added: 41688, mode: MaxEncodedLen)
	fn fast_track_scheduled_dispatch() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1188`
		//  Estimated: `87879`
		// Minimum execution time: 43_873 nanoseconds.
		Weight::from_parts(44_470_000, 87879)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	// Storage: Scheduler Lookup (r:1 w:1)
	// Proof: Scheduler Lookup (max_values: None, max_size: Some(48), added: 2523, mode: MaxEncodedLen)
	// Storage: Scheduler Agenda (r:2 w:2)
	// Proof: Scheduler Agenda (max_values: None, max_size: Some(39213), added: 41688, mode: MaxEncodedLen)
	fn delay_scheduled_dispatch() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1188`
		//  Estimated: `87879`
		// Minimum execution time: 43_551 nanoseconds.
		Weight::from_parts(44_252_000, 87879)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	// Storage: Scheduler Lookup (r:1 w:1)
	// Proof: Scheduler Lookup (max_values: None, max_size: Some(48), added: 2523, mode: MaxEncodedLen)
	// Storage: Scheduler Agenda (r:1 w:1)
	// Proof: Scheduler Agenda (max_values: None, max_size: Some(39213), added: 41688, mode: MaxEncodedLen)
	fn cancel_scheduled_dispatch() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1188`
		//  Estimated: `46191`
		// Minimum execution time: 33_898 nanoseconds.
		Weight::from_parts(34_644_000, 46191)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	// Storage: Authority SavedCalls (r:0 w:1)
	// Proof Skipped: Authority SavedCalls (max_values: None, max_size: None, mode: Measured)
	fn authorize_call() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `965`
		//  Estimated: `965`
		// Minimum execution time: 17_143 nanoseconds.
		Weight::from_parts(17_633_000, 965)
			.saturating_add(T::DbWeight::get().writes(1))
	}
	// Storage: Authority SavedCalls (r:1 w:1)
	// Proof Skipped: Authority SavedCalls (max_values: None, max_size: None, mode: Measured)
	fn remove_authorized_call() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1306`
		//  Estimated: `4771`
		// Minimum execution time: 22_508 nanoseconds.
		Weight::from_parts(23_104_000, 4771)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	// Storage: Authority SavedCalls (r:1 w:1)
	// Proof Skipped: Authority SavedCalls (max_values: None, max_size: None, mode: Measured)
	fn trigger_call() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1306`
		//  Estimated: `4771`
		// Minimum execution time: 28_812 nanoseconds.
		Weight::from_parts(29_221_000, 4771)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
